# Site settings
title: Eventbrite Test
email: david.osborn@angelsolutions.co.uk
description:
baseurl: "/event-test"
twitter_username:
github_username:

# Build settings
markdown: redcarpet
encoding: utf-8
highlighter: rouge
permalink: /:year/:month/:title
paginate: 10
exclude: ["node_modules", "app-js", "README.md"]